# Generated by Django 5.2.8 on 2025-12-28 12:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField(blank=True, null=True)),
                ('current_title', models.TextField(blank=True, null=True)),
                ('current_company', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'new'), ('in_review', 'in_review'), ('shortlisted', 'shortlisted'), ('rejected', 'rejected'), ('hired', 'hired')], default='new', max_length=20)),
                ('source', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'candidates',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('slug', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='RankingRun',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criteria_json', models.JSONField()),
                ('bias_config_json', models.JSONField(blank=True, null=True)),
                ('model_name', models.TextField(blank=True, null=True)),
                ('model_version', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('completed', 'completed'), ('failed', 'failed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ranking_runs',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='SearchDocument',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('candidate', 'candidate'), ('cv_parse', 'cv_parse'), ('other', 'other')], max_length=20)),
                ('entity_id', models.UUIDField()),
                ('source_text', models.TextField(blank=True, null=True)),
                ('embedding_json', models.JSONField(blank=True, null=True)),
                ('index_backend', models.CharField(choices=[('elasticsearch', 'elasticsearch'), ('opensearch', 'opensearch'), ('other', 'other')], default='elasticsearch', max_length=20)),
                ('index_status', models.CharField(choices=[('pending', 'pending'), ('indexed', 'indexed'), ('failed', 'failed')], default='pending', max_length=20)),
                ('indexed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'search_documents',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user_roles',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_hash',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.CreateModel(
            name='CVFile',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('upload', 'upload'), ('email', 'email'), ('linkedin', 'linkedin'), ('other', 'other')], default='upload', max_length=20)),
                ('storage_path', models.TextField()),
                ('original_filename', models.TextField()),
                ('mime_type', models.TextField(blank=True, null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('checksum', models.TextField(blank=True, null=True)),
                ('upload_status', models.CharField(choices=[('uploaded', 'uploaded'), ('failed', 'failed')], default='uploaded', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_files', to='accounts.candidate')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_files', to='accounts.organization')),
            ],
            options={
                'db_table': 'cv_files',
            },
        ),
        migrations.CreateModel(
            name='CVParse',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parse_status', models.CharField(choices=[('pending', 'pending'), ('succeeded', 'succeeded'), ('failed', 'failed')], default='pending', max_length=20)),
                ('parser_name', models.TextField(blank=True, null=True)),
                ('parser_version', models.TextField(blank=True, null=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('cv_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_parses', to='accounts.cvfile')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_parses', to='accounts.organization')),
            ],
            options={
                'db_table': 'cv_parses',
            },
        ),
        migrations.CreateModel(
            name='CVAccessEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('viewed', 'viewed'), ('forwarded', 'forwarded'), ('uploaded', 'uploaded'), ('parse_started', 'parse_started'), ('parse_finished', 'parse_finished'), ('ranked', 'ranked'), ('searched', 'searched'), ('summary_generated', 'summary_generated')], max_length=30)),
                ('channel', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cv_access_events', to=settings.AUTH_USER_MODEL)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_access_events', to='accounts.candidate')),
                ('cv_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cv_access_events', to='accounts.cvfile')),
                ('cv_parse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cv_access_events', to='accounts.cvparse')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_access_events', to='accounts.organization')),
            ],
            options={
                'db_table': 'cv_access_events',
            },
        ),
        migrations.CreateModel(
            name='CandidateSummary',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('summary_status', models.CharField(choices=[('pending', 'pending'), ('succeeded', 'succeeded'), ('failed', 'failed')], default='pending', max_length=20)),
                ('language', models.TextField(default='hu')),
                ('model_name', models.TextField(blank=True, null=True)),
                ('model_version', models.TextField(blank=True, null=True)),
                ('prompt_version', models.TextField(blank=True, null=True)),
                ('summary_text', models.TextField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='accounts.candidate')),
                ('cv_parse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summaries', to='accounts.cvparse')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_summaries', to='accounts.organization')),
            ],
            options={
                'db_table': 'candidate_summaries',
            },
        ),
        migrations.CreateModel(
            name='CandidateStructuredData',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('structured_json', models.JSONField(default=dict)),
                ('headline', models.TextField(blank=True, null=True)),
                ('primary_location', models.TextField(blank=True, null=True)),
                ('top_skills', models.TextField(blank=True, null=True)),
                ('experience_years', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('cv_parse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='structured_data', to='accounts.cvparse')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_structured_data', to='accounts.organization')),
            ],
            options={
                'db_table': 'candidate_structured_data',
            },
        ),
        migrations.CreateModel(
            name='CandidateScore',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('details_json', models.JSONField(blank=True, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_scores', to='accounts.candidate')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_scores', to='accounts.organization')),
            ],
            options={
                'db_table': 'candidate_scores',
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='accounts.organization'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('log', 'log'), ('debug', 'debug'), ('verbose', 'verbose')], default='log', max_length=20)),
                ('event_type', models.TextField()),
                ('entity_type', models.TextField()),
                ('entity_id', models.UUIDField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='accounts.organization')),
            ],
            options={
                'db_table': 'audit_logs',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.organization'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('organization', 'email'), name='users_org_email_unique'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='users_org_id_unique'),
        ),
        migrations.AddField(
            model_name='rankingrun',
            name='created_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ranking_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rankingrun',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_runs', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='candidatescore',
            name='ranking_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_scores', to='accounts.rankingrun'),
        ),
        migrations.AddField(
            model_name='searchdocument',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_documents', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='user_roles', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='cvparse',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='cv_parses_org_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='cvfile',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='cv_files_org_id_unique'),
        ),
        migrations.AddIndex(
            model_name='cvaccessevent',
            index=models.Index(fields=['organization', 'created_at'], name='cv_access_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='cvaccessevent',
            index=models.Index(fields=['candidate', 'created_at'], name='cv_access_cand_created_idx'),
        ),
        migrations.AddIndex(
            model_name='candidatesummary',
            index=models.Index(fields=['candidate'], name='cand_sum_cand_idx'),
        ),
        migrations.AddConstraint(
            model_name='candidatesummary',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='candidate_summaries_org_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='candidatestructureddata',
            constraint=models.UniqueConstraint(fields=('cv_parse',), name='candidate_structured_data_cv_parse_unique'),
        ),
        migrations.AddConstraint(
            model_name='candidatestructureddata',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='candidate_structured_data_org_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('organization', 'email'), name='candidates_org_email_unique'),
        ),
        migrations.AddConstraint(
            model_name='candidate',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='candidates_org_id_unique'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', 'created_at'], name='audit_logs_org_created_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['event_type', 'created_at'], name='audit_logs_event_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='rankingrun',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='ranking_runs_org_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='candidatescore',
            constraint=models.UniqueConstraint(fields=('ranking_run', 'candidate'), name='candidate_scores_run_candidate_unique'),
        ),
        migrations.AddConstraint(
            model_name='candidatescore',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='candidate_scores_org_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='searchdocument',
            constraint=models.UniqueConstraint(fields=('organization', 'entity_type', 'entity_id'), name='search_documents_org_entity_unique'),
        ),
        migrations.AddConstraint(
            model_name='searchdocument',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='search_documents_org_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('organization', 'user', 'role'), name='user_roles_org_user_role_unique'),
        ),
        migrations.AddConstraint(
            model_name='userrole',
            constraint=models.UniqueConstraint(fields=('organization', 'id'), name='user_roles_org_id_unique'),
        ),
    ]
