"""Predefined lists of entities for entity extraction."""


PROGRAMMING_LANGUAGES = {
    "python",
    "java",
    "javascript",
    "typescript",
    "c++",
    "c#",
    "c",
    "ruby",
    "php",
    "swift",
    "kotlin",
    "go",
    "golang",
    "rust",
    "scala",
    "r",
    "perl",
    "matlab",
    "julia",
    "dart",
    "haskell",
    "lua",
    "groovy",
    "objective-c",
    "visual basic",
    "vb.net",
    "f#",
    "bash",
    "shell",
    "powershell",
    "sql",
    "plsql",
    "t-sql",
    "assembly",
    "fortran",
    "cobol",
}

FRAMEWORKS = {
    # Python
    "django",
    "flask",
    "fastapi",
    "pyramid",
    "tornado",
    "pandas",
    "numpy",
    "scipy",
    "scikit-learn",
    "sklearn",
    "tensorflow",
    "keras",
    "pytorch",
    "opencv",
    "matplotlib",
    "seaborn",
    "plotly",
    "streamlit",
    "celery",
    "airflow",
    "scrapy",
    "beautifulsoup",
    "requests",
    # JavaScript/TypeScript
    "react",
    "react.js",
    "reactjs",
    "angular",
    "vue",
    "vue.js",
    "vuejs",
    "node.js",
    "nodejs",
    "express",
    "express.js",
    "next.js",
    "nextjs",
    "nuxt",
    "nuxt.js",
    "svelte",
    "ember",
    "backbone",
    "jquery",
    "electron",
    "d3.js",
    "three.js",
    "nest.js",
    "nestjs",
    # Java
    "spring",
    "spring boot",
    "hibernate",
    "struts",
    "jsp",
    "jsf",
    "maven",
    "gradle",
    "junit",
    "testng",
    # .NET
    "asp.net",
    ".net",
    ".net core",
    "entity framework",
    "xamarin",
    "blazor",
    "wpf",
    "winforms",
    # Mobile
    "react native",
    "flutter",
    "ionic",
    "cordova",
    # Other
    "laravel",
    "symfony",
    "codeigniter",
    "rails",
    "ruby on rails",
    "sinatra",
    "gin",
    "echo",
    "fiber",
    "actix",
    "rocket",
}

DATABASES = {
    # SQL
    "mysql",
    "postgresql",
    "postgres",
    "sqlite",
    "oracle",
    "sql server",
    "mariadb",
    "db2",
    "sybase",
    "teradata",
    "snowflake",
    # NoSQL
    "mongodb",
    "cassandra",
    "redis",
    "couchdb",
    "neo4j",
    "dynamodb",
    "elasticsearch",
    "solr",
    "influxdb",
    "firebase",
    "firestore",
    # Vector DBs
    "chromadb",
    "chroma",
    "pinecone",
    "weaviate",
    "milvus",
    "qdrant",
    "faiss",
}

CLOUD_PLATFORMS = {
    "aws",
    "amazon web services",
    "azure",
    "microsoft azure",
    "gcp",
    "google cloud",
    "google cloud platform",
    "heroku",
    "digitalocean",
    "linode",
    "ibm cloud",
    "oracle cloud",
    "alibaba cloud",
    "cloudflare",
    "vercel",
    "netlify",
}

TOOLS = {
    # Version Control
    "git",
    "github",
    "gitlab",
    "bitbucket",
    "svn",
    "mercurial",
    # DevOps & CI/CD
    "docker",
    "kubernetes",
    "k8s",
    "jenkins",
    "circleci",
    "travis ci",
    "github actions",
    "gitlab ci",
    "terraform",
    "ansible",
    "puppet",
    "chef",
    "vagrant",
    "nginx",
    "apache",
    "iis",
    # Testing
    "selenium",
    "cypress",
    "jest",
    "mocha",
    "chai",
    "pytest",
    "unittest",
    "testng",
    "junit",
    "postman",
    "jmeter",
    # IDEs & Editors
    "vscode",
    "visual studio",
    "intellij",
    "pycharm",
    "webstorm",
    "eclipse",
    "netbeans",
    "sublime",
    "atom",
    "vim",
    "emacs",
    # Project Management
    "jira",
    "confluence",
    "trello",
    "asana",
    "monday.com",
    # Other
    "webpack",
    "babel",
    "eslint",
    "prettier",
    "swagger",
    "graphql",
    "rest api",
    "soap",
    "grpc",
    "kafka",
    "rabbitmq",
}

SOFT_SKILLS = {
    "leadership",
    "team player",
    "communication",
    "problem solving",
    "analytical thinking",
    "critical thinking",
    "creativity",
    "time management",
    "project management",
    "agile",
    "scrum",
    "collaboration",
    "adaptability",
    "flexibility",
    "work ethic",
    "attention to detail",
    "multitasking",
    "decision making",
    "conflict resolution",
    "mentoring",
    "coaching",
    "presentation",
    "negotiation",
    "customer service",
    "interpersonal skills",
}

NATURAL_LANGUAGES = {
    "english",
    "spanish",
    "french",
    "german",
    "italian",
    "portuguese",
    "chinese",
    "mandarin",
    "japanese",
    "korean",
    "arabic",
    "russian",
    "hindi",
    "bengali",
    "dutch",
    "swedish",
    "polish",
    "turkish",
    "vietnamese",
    "thai",
    "greek",
    "hebrew",
    "hungarian",
    "czech",
    "romanian",
    "ukrainian",
    "danish",
    "norwegian",
    "finnish",
}

DEGREE_PATTERNS = {
    "bachelor",
    "b.s.",
    "b.a.",
    "b.sc.",
    "b.tech",
    "b.e.",
    "master",
    "m.s.",
    "m.a.",
    "m.sc.",
    "m.tech",
    "m.e.",
    "mba",
    "ph.d.",
    "phd",
    "doctorate",
    "associate",
    "diploma",
    "certificate",
    "certification",
}

JOB_TITLES = {
    "software engineer",
    "software developer",
    "full stack developer",
    "frontend developer",
    "backend developer",
    "web developer",
    "mobile developer",
    "data scientist",
    "data analyst",
    "data engineer",
    "machine learning engineer",
    "ai engineer",
    "devops engineer",
    "cloud engineer",
    "security engineer",
    "qa engineer",
    "test engineer",
    "product manager",
    "project manager",
    "scrum master",
    "tech lead",
    "team lead",
    "architect",
    "solutions architect",
    "principal engineer",
    "senior engineer",
    "junior engineer",
    "intern",
    "consultant",
    "analyst",
    "administrator",
    "coordinator",
}

# --- HUNGARIAN KEYWORDS ---

DEGREE_PATTERNS_HU = {
    "alapdiploma",
    "főiskolai diploma",
    "egyetemi diploma",
    "bsc",
    "msc",
    "mesterdiploma",
    "doktori",
    "phd",
    "oklevél",
    "bizonyítvány",
    "szakképesítés",
    "mérnök informatikus",
    "programtervező informatikus",
    "gazdaságinformatikus",
}

JOB_TITLES_HU = {
    "szoftverfejlesztő",
    "szoftvermérnök",
    "frontend fejlesztő",
    "backend fejlesztő",
    "full-stack fejlesztő",
    "webfejlesztő",
    "mobilfejlesztő",
    "adattudós",
    "adatelemző",
    "adatmérnök",
    "gépi tanulás mérnök",
    "devops mérnök",
    "tesztmérnök",
    "projektmenedzser",
    "scrum master",
    "csapatvezető",
    "vezető fejlesztő",
    "szenior fejlesztő",
    "junior fejlesztő",
    "gyakornok",
    "tanácsadó",
    "elemző",
    "rendszergazda",
    "koordinátor",
    "hr menedzser",
    "toborzó",
}

SOFT_SKILLS_HU = {
    "vezetői készség",
    "csapatjátékos",
    "kommunikáció",
    "problémamegoldás",
    "analitikus gondolkodás",
    "kritikus gondolkodás",
    "kreativitás",
    "időgazdálkodás",
    "projektmenedzsment",
    "agilis",
    "scrum",
    "együttműködés",
    "alkalmazkodóképesség",
    "rugalmasság",
    "munkamorál",
    "részletekre való odafigyelés",
    "döntéshozatal",
    "konfliktuskezelés",
    "prezentáció",
    "tárgyalás",
    "ügyfélkiszolgálás",
}

# --- COMBINED KEYWORDS (English + Hungarian) ---

ALL_DEGREE_PATTERNS = DEGREE_PATTERNS | DEGREE_PATTERNS_HU
ALL_JOB_TITLES = JOB_TITLES | JOB_TITLES_HU
ALL_SOFT_SKILLS = SOFT_SKILLS | SOFT_SKILLS_HU

