# Generated by Django 5.2.10 on 2026-01-19 17:24

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_candidate_organization_rankingrun_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchdocument',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
