# Generated by Django 5.2.10 on 2026-01-21 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_vector_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('employer', 'Employer/Recruiter'), ('job_seeker', 'Job Seeker')], default='employer', help_text='Type of user: employer (has organization) or job seeker (individual)', max_length=20),
        ),
    ]
